name: Android Debug APK (hard no-ci install)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-android-debug:
    runs-on: ubuntu-latest
    env:
      CI: true                 # non-interactive für Expo
      EXPO_NO_TELEMETRY: 1
      npm_config_ci: "false"   # verhindert jegliches ci-Verhalten von npm

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug: list files
        run: |
          pwd
          ls -la
          node -v || true
          npm -v || true

      - name: Setup Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      # *** WICHTIG: Lockfile weg und verifizieren ***
      - name: Remove lockfile (force fresh resolve)
        run: |
          rm -f package-lock.json
          if [ -f package-lock.json ]; then echo "lockfile still present"; exit 1; else echo "no lockfile"; fi

      # *** HART: Niemals npm ci, nur install – mit legacy peer deps ***
      - name: Install deps (robust)
        env:
          npm_config_legacy_peer_deps: "true"
          npm_config_audit: "false"
          npm_config_fund: "false"
        run: |
          npm install --loglevel=warn --no-optional
          echo "lockfile status:"
          if [ -f package-lock.json ]; then echo "lockfile created"; else echo "no lockfile created"; fi

      - name: Align to Expo SDK (optional)
        run: npx expo install --fix || true

      # Kein --non-interactive Flag; CI=1 übernimmt das
      - name: Prebuild Android (generate android/)
        run: npx expo prebuild --platform android --no-install

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build Debug APK
        run: |
          cd android
          ./gradlew assembleDebug --no-daemon

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk
