name: Android Debug APK (npm robust)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-android-debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Relax peer deps
        run: npm config set legacy-peer-deps true

      - name: Install deps (npm)
        run: npm install --no-audit --no-fund --loglevel=warn

      - name: Expo install --fix (best match to SDK)
        run: npx expo install --fix || true

      - name: Expo prebuild (android/)
        run: npx expo prebuild --platform android --non-interactive

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build Debug APK
        run: |
          cd android
          ./gradlew assembleDebug --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk
