name: Android Debug APK (npm robust)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-android-debug:
    runs-on: ubuntu-latest
    env:
      CI: true   # <- wichtig: non-interactive Modus für Expo

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

- name: Remove lockfile (force fresh resolve)
  run: rm -f package-lock.json

- name: Install deps (robust)
  run: |
    npm config set legacy-peer-deps true
    npm install --no-audit --no-fund --loglevel=warn --no-optional

- name: Align to Expo SDK (optional)
  run: npx expo install --fix || true


      - name: Align to Expo SDK (optional)
        run: npx expo install --fix || true

      # Wichtig: kein --non-interactive verwenden; CI=1 übernimmt das
      - name: Prebuild Android (generate android/)
        run: npx expo prebuild --platform android --no-install

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build Debug APK
        run: |
          cd android
          ./gradlew assembleDebug --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk
