name: Android Debug APK (npm robust)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-android-debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      # Wenn Lockfile vorhanden -> npm ci, sonst fallback auf npm install
      - name: Install deps (prefer ci)
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm config set legacy-peer-deps true
            npm install --no-audit --no-fund --loglevel=warn
          fi

      - name: Expo install --fix
        run: npx expo install --fix || true

      - name: Prebuild Android (generate android/)
        run: npx expo prebuild --platform android --non-interactive

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build Debug APK
        run: |
          cd android
          ./gradlew assembleDebug --no-daemon

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk
